# ==================================================================================================
# Conda Recipe for loretex - Release Version
#
# Detailed recipe intended for automated builds and deployment to the static conda channel.
#
# It fetches the package from a specific Git tag, installs it using pip, and defines complete
# metadata required for public distribution and reproducibility.
#
# Usage
# -----
# To build the package for release, run the following command from the project root directory:
#
# ```sh
# conda build conda.recipe.release/
# ```
#
# Notes
# -----
# - The version is defined via a Jinja2 variable (`{% set version = ... %}`).
# - The source is retrieved from a specific GitHub tag.
# - The license file and metadata fields must be consistent with the repository.
# - This file is used in CI/CD workflows for deployment to `eresthina-conda-channel`.
# ==================================================================================================
{% set version = "0.1.0" %}

package:
  name: loretex
  version: {{ version }}

source:
  git_url: https://github.com/esther-poniatowski/loretex.git
  git_tag: v0.1.0

build:
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools >=61
    - wheel
  run:
    - python >=3.12
    - pyyaml
    - markdown-it-py
    - attrs
    - typer
    - rich

test:
  commands:
    - loretex --help
  imports:
    - loretex

about:
  summary: "Converter between Markdown notes and LaTeX files."
  license: GPL-3.0-or-later
  license_file: LICENSE
  home: https://github.com/esther-poniatowski/loretex
  description: |
    Command-line tool for converting structured Markdown notes into LaTeX documents.

extra:
  recipe-maintainers:
    - esther-poniatowski
